name: djangoflow_analytics
description: A library for tracking analytics with multiple Analytics providers in Flutter applications.
version: 0.1.0
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_analytics/djangoflow_analytics

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  analytics: ^1.0.2
  flutter:
    sdk: flutter

  mockito: ^5.3.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
