name: djangoflow_auth_facebook
description: djangoflow_auth_facebook adds a touch of Facebook magic to your Flutter app with Djangoflow API
version: 0.2.0
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_auth/djangoflow_auth_facebook

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  djangoflow_auth: ^0.6.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^7.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
