name: djangoflow_app
description: A simple, opinionated, and minimal Flutter application structure for quick start and easy maintenance.
version: 3.2.0
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  package_info_plus: ^4.0.2
  path_provider: ^2.0.15
  hydrated_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
  freezed: ^2.3.5
  json_serializable: ^6.7.0
