name: djangoflow_app
description: Djangoflow app with firebase support.
version: 1.0.3
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  app_tracking_transparency: ^2.0.2+4
  auto_route: ^4.2.1
  facebook_app_events: ^0.16.0
  firebase_analytics: ^9.3.1
  firebase_core: ^1.20.1
  firebase_messaging: ^12.0.2
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.1.0
  hydrated_bloc: ^8.1.0
  json_annotation: ^4.6.0
  mixpanel_flutter: ^1.5.1
  package_info_plus: ^1.4.3+1
  path_provider: ^2.0.11
  sentry_flutter: ^6.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
