name: djangoflow_auth_google
description: djangoflow_auth_google is the Google authentication provider for djangoflow_auth package
version: 0.2.0
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_auth/djangoflow_auth_google

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  djangoflow_auth: ^0.6.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  google_sign_in: ^6.2.2
  google_sign_in_platform_interface: ^2.4.5
  google_sign_in_web: ^0.12.4+3
  json_annotation: ^4.9.0
  mounted_state: ^1.0.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
