name: djangoflow_auth_discord
description: djangoflow_auth_discord brings the power of Discord authentication to your Flutter app!
version: 0.2.0+1
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_auth/djangoflow_auth_discord

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  djangoflow_auth: ^0.6.0+1
  flutter:
    sdk: flutter
  http: ^1.2.2
  oauth2_client: ^3.3.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
