name: djangoflow_auth_discord
description: djangoflow_auth_discord brings the power of Discord authentication to your Flutter app!
version: 0.0.4+6
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  djangoflow_auth: ^0.2.1+3
  djangoflow_openapi: ^0.0.18
  oauth2_client: ^3.2.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  mockito: ^5.4.2

dependency_overrides:
  # Due to oauth2_client does not support http: ^1.0.0
  # Can be removed one https://github.com/teranetsrl/oauth2_client/pull/168 merged
  http: ^1.0.0

flutter:
