name: example
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  djangoflow_local_notification:
    path: ../
  flutter_local_notifications: ^17.2.1+2
  djangoflow_openapi: ^0.1.22
  flutter_bloc: ^8.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
