name: chat
description: A flutter application demonstrating integration of djangoflow_chat and [https://github.com/djangoflow/django-df-chat](django-df-chat)

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  openapi:
    path: ../openapi
  djangoflow_chat:
    path: ../../../../djangoflow_chat
  auto_route: ^5.0.4
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  characters: ^1.2.1
  collection: ^1.17.0
  countdown_widget: ^2.0.2
  dio: ^5.0.2
  djangoflow_app: ^3.0.0
  djangoflow_app_links: ^1.1.3
  flutter_bloc: ^8.1.1
  flutter_chat_types: ^3.6.0
  flutter_chat_ui: ^1.6.6
  firebase_core: ^2.4.1
  flex_color_scheme: ^6.1.2

  flutter_list_bloc: ^4.0.1
  freezed_annotation: ^2.2.0

  hydrated_bloc: ^9.0.0
  json_annotation: ^4.7.0
  list_bloc: ^3.1.0
  modal_bottom_sheet: ^3.0.0-pre
  openapi_repository_annotations: ^1.1.0
  package_info_plus: ^3.0.2
  path_provider: ^2.0.11
  progress_builder: ^1.1.3
  reactive_forms: ^14.1.0
  responsive_framework: ^0.2.0
  upgrader: ^6.2.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  icons_launcher: ^2.0.7
  json_serializable: ^6.5.4
  openapi_repository: ^2.0.0

dependency_overrides:
  # Conflict for icons_launcher and flutter_test
  path: 1.8.2
  # Conflict with flutter_test and test packages
  test_api: 0.4.18
  # Until null check error fixed pushed https://github.com/Milad-Akarie/auto_route_library/pull/1301
  auto_route:
    git:
      url: "https://github.com/djangoflow/auto_route_library.git"
      ref: master
      path: "auto_route"
  auto_route_generator:
    git:
      url: "https://github.com/djangoflow/auto_route_library.git"
      ref: master
      path: "auto_route_generator"
  openapi:
    path: ../openapi

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo/
