name: djangoflow_sync_drift_odoo
description: "Odoo Sync package for Flutter using Drift"
version: 0.2.0+1
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_odoo/sync/djangoflow_sync_drift_odoo

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  djangoflow_sync_foundation: ^0.1.0+2
  drift: ^2.21.0
  flutter:
    sdk: flutter
  odoo_rpc:
    git:
      url: https://github.com/djangoflow/odoo-rpc-dart.git
      ref: master
  recase: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.13
  drift_dev: ^2.21.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter