name: djangoflow_auth
description: djangoflow_auth is your ultimate Flutter authentication companion, packed with Djangoflow API supports.
version: 0.3.0
homepage: https://github.com/djangoflow/flutter-djangoflow/

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.2
  collection: ^1.17.1
  dio: ^5.3.2
  djangoflow_openapi: ^0.0.21
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  hydrated_bloc: ^9.1.2
  universal_html: ^2.2.3
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  mocktail: ^1.0.0

flutter:
