name: djangoflow_emoji_rain
description: A Flutter package for creating a delightful rain of emojis on your screen.
version: 0.1.0
homepage: https://github.com/djangoflow/flutter-djangoflow/tree/main/packages/djangoflow_emoji_rain

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mounted_state: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0